### ISSUE TITLE
添加之后无法使用

### ISSUE THREAD

**Issue by 495luke** [SonderXiaoming/hunnai_eitherchoice#2]
启动hoshino的时候cmd有报错 ERROR: Failed to import "hoshino.modules.hunnai_eitherchoice.data_source", error: No module named 'markdown'，无法触发，使用lssv查看启用的服务之后发现lssv里面没有“AI锐评”这个服务。是需要安装依赖吗？

**Comment by SonderXiaoming** [comment]
是，装到不报错为止，具体可以google

**Comment by SonderXiaoming** [comment]
直接搜No module named 'markdown'
